branches:
    only:
        - master

cache:
    directories:
        - $HOME/cache
    
sudo: required

services:
    - docker

before_install:
    - docker build -t webapp:test -f ./dockerfile/test .

script:
    - docker run -it --rm -v $HOME/publish:/root/publish -v $HOME/cache:/root/.nuget/packages webapp:test

after_success:
    - docker build -t webapp:release -f ./dockerfile/release 